### ISSUE TITLE
Implement Core Team GPG key for passwordstore

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#1041]

**Comment by jacobdotcosta** [comment]
Snowdrop Core team GPG key created and pushed to the passwordstore.

GPG Public Key

```
├── gpg-keys
│   └── snowdrop-core@redhat.com
```


GPG Private Key

```
├── snowdrop
│   └── snowdrop-core@redhat.com.private.key
```

Passphrase

```
├── snowdrop
│   ├── snowdrop-core@redhat.com.passphrase
```

@cmoulliard

**Comment by jacobdotcosta** [comment]
As this key is added to the passwordstore index it's required to import this GPG key to be able to keep using the passwordstore. For more information check the [All the other members import the key of the new member](https://github.com/snowdrop/pass#adding-a-new-member) section of the pass project documentation.

**Comment by cmoulliard** [comment]
Take care to mention within the email that 2 steps are needed:
- Import the new snowdrop core gpg key
- Trust the newly imported public key

**Comment by jacobdotcosta** [comment]
> Take care to mention within the email that 2 steps are needed:
> 
> * Import the new snowdrop core gpg key
> * Trust the newly imported public key

Added a comment about this just before you posted this message.
