### ISSUE TITLE
Check redhat-buildpacks / testing error

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#1071]

**Comment by jacobdotcosta** [comment]
Tekton testing execution workflows: https://github.com/redhat-buildpacks/testing/actions/workflows/tekton.yaml

**Comment by jacobdotcosta** [comment]
✅ 269: https://github.com/redhat-buildpacks/testing/actions/runs/6156814542 
❌ 270: https://github.com/redhat-buildpacks/testing/actions/runs/6157879627

```diff
- curl -sOL https://raw.githubusercontent.com/redhat-buildpacks/catalog/main/tekton/pipelinerun/rhtap/pipelinerun-buildpacks-ref-template.yaml
- mv pipelinerun-buildpacks-ref-template.yaml .tekton/$GITHUB_REPO_DEMO_NAME-push.yaml

+ curl -sOL https://raw.githubusercontent.com/redhat-buildpacks/catalog/main/tekton/pipelinerun/rhtap/pipelinerun-buildpacks-template.yaml
+ mv pipelinerun-buildpacks-template.yaml .tekton/$GITHUB_REPO_DEMO_NAME-push.yaml
```

**Comment by cmoulliard** [comment]
Can be closed as the problem has been fixed normally `invalid input params for task buildpacks-phases: missing values for these params which have no default values: [CNB_RUN_IMAGE]`
