### ISSUE TITLE
Review Ansible role documentation

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#13]
Check:
- [x] [Question] How should we generate the roles's documentation ? - [snowdrop/k8s-infra issue-151](https://github.com/snowdrop/k8s-infra/issues/151)
- [x] Add project generating table of roles using asciidoctor - [snowdrop/k8s-infra PR-161](https://github.com/snowdrop/k8s-infra/pull/161)

**Comment by cmoulliard** [comment]
I think that we did this work or do I miss something ? @jacobdotcosta

**Comment by jacobdotcosta** [comment]
Yes, I'll move it to closed.
