### ISSUE TITLE
Check impact of building and productizing dekorate independently from the spring-boot project

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#150]
Dekorate is the only non-spring-boot library being productized from within the spring-boot project. Check what impact would making dekorate independent have on both projects.

**Comment by jacobdotcosta** [comment]
Ezquiel commented on the weekly meeting that Dekorate won't be productized independently for now.

**Comment by cmoulliard** [comment]
This ticket should be discussed for next release 2.3 and if changes are needed, then a grooming request is required. Can you add this point to the agenda of the weekly call for next week please @jacobdotcosta ?

**Comment by jacobdotcosta** [comment]
We discussed this at the meeting and it has been discarded for now.
