### ISSUE TITLE
Migrate all Spring Boot Examples to use Dekorate instead of Fabric8

### ISSUE THREAD

**Issue by iocanel** [snowdrop/team#156]
List of repositories using Fabric8 that need to be migrated to Dekorate:

- https://github.com/snowdrop/cache-example
- https://github.com/snowdrop/circuit-breaker-example
- https://github.com/snowdrop/configmap-example
- https://github.com/snowdrop/crud-example
- https://github.com/snowdrop/health-check-example
- https://github.com/snowdrop/istio-distributed-tracing-example
- https://github.com/snowdrop/messaging-work-queue-example
- https://github.com/snowdrop/rest-http-example
- https://github.com/snowdrop/secured-example

Migrating to Dekorate also implies:
- Drop Fabric8 Maven and Arquillian dependencies
- Use JUnit 5 instead of JUnit 4
- Update scripts and documentation

**Comment by Sgitario** [comment]
All examples have been migrated to use Dekorate (only the branch sb 2.4). Closing.
