### ISSUE TITLE
Migration to Fedora OS

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop/team#176]
I need to migrate my laptop to fedora OS. RHEL is to much closed and I don't have control over a lot of things.

**Comment by cmoulliard** [comment]
Did you succeeded ? @aureamunoz

**Comment by aureamunoz** [comment]
I did the backup and burned a drive with the image to install, I'm installing it this evening I think

**Comment by cmoulliard** [comment]
Installed now ?

**Comment by aureamunoz** [comment]
No, because I had to work on the 2.1.15 release and as Antonio was in PTO I wanted to be sure to be able to do it
