### ISSUE TITLE
Spring on Quarkus / DevExp / KNative Serving level up skills

### ISSUE THREAD

**Issue by geoand** [snowdrop/team#177]
I need to level up my knowledge of KNative

**Comment by cmoulliard** [comment]
Can you please elaborate, provide a description about what should be achieve under this issue ? Is it an issue or an epic ... ? @geoand

**Comment by geoand** [comment]
Well, it's not about the team achieving anything, it's about me learning more about knative :)

**Comment by cmoulliard** [comment]
My fault. Description message was clear ;-) We should have another missing label for `xx - R&D` Can you check and propose something for the team ? Chris did something about that I think so ...

**Comment by geoand** [comment]
I agree, a different label would be nice. I'll ask the team

**Comment by cmoulliard** [comment]
As team will work on `spring-cloud-function-event-starter` and knowledge sharing will be more than a plus, I suggest then that we setup a bi-weekly discussion with team in order to exchange, demo Knative, Function and Event. WDYT ? @geoand

**Comment by geoand** [comment]
Sure, but I don't plan on leading that (not initially at least). At this point Ioannis knows the most, I am just trying to catch up 😉
