### ISSUE TITLE
 Spring on Quarkus / Advocation / Record Spring on Quarkus demo

### ISSUE THREAD

**Issue by geoand** [snowdrop/team#188]
Markus Eisele asked me to do a Spring on Quarkus recording for BrightTalk.

Points to show:

* Spring APIs with Quarkus
* Combine Spring with MP APIs

**Comment by cmoulliard** [comment]
Can you please elaborate using a bullets list what you plan to do, scenario, project, .. @geoand

**Comment by geoand** [comment]
Done
