### ISSUE TITLE
Productization / 2.2.6.SP2 - Retrospective

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#254]
- The upstream project was not modified.
- The idea was to release before PNC 2 reached production.
- The marete tests failed with missing dependencies:
  - I thought we had to wait until the jars reached Maven Central.
  - Later Libor clarified that the problem was due to the previous release, `2.1.15` if I'm not mistaken, which had a different pom structure. This required an update to the marete tests to adapt to the 2.2.x pom structure. 
- With this delay we missed the the PNC 2 production date.
- After all PNC 2 mayhem... 
- Investigated and tested on the fly the new PNC CLI (`bacon`) to have it running on Jenkins
  - After lot's of disappointing work testing PNC 2 and bacon...
  - Finally the launching of the build was made on my laptop because when launching bacon on the Jenkins Job it failed.
- Libor detected that the dekorate version was wrong. It should have been `1.0.0.redhat-00002` but was `1.0.0.redhat-00001`.
  - This problem was dragged by the SP1 release. We had some problems with the generated files and I did some tests to try overriding the dekorate file to be downloaded in the sources. After all those failed attempts I forgot to update dekorate back to `1.0.0.redhat-00002`.
- On the update of the launcher-booster-catalog Chris realized that the upstream examples were wrong. This happened because I didn't launch the `update for release` command after releasing the upstream project.

**Comment by cmoulliard** [comment]
> * This required an update to the marete tests to adapt to the 2.2.x pom structure.

Do we have to do this marete modification to the code before to do the PNC build of 2.3.x ? If yes, do we have a ticket created describing what should be done? @jacobdotcosta

**Comment by cmoulliard** [comment]
> * Libor detected that the dekorate version was wrong.

Is it fixed or this problem will be back for the release 2.3.X ? What can we do in the future to control/check before to build ? @jacobdotcosta

**Comment by cmoulliard** [comment]
> * On the update of the launcher-booster-catalog Chris realized that the upstream examples were wrong. This happened because I didn't launch the `update for release` command after releasing the upstream project.

How can we avoid that for a future release ? @jacobdotcosta

**Comment by jacobdotcosta** [comment]
> > * This required an update to the marete tests to adapt to the 2.2.x pom structure.
> 
> Do we have to do this marete modification to the code before to do the PNC build of 2.3.x ? If yes, do we have a ticket created describing what should be done? @jacobdotcosta

It was a change between 2.1 and later 2.2, 2.3, ... versions so if we don't productize 2.1 again we won't have to change it.

**Comment by jacobdotcosta** [comment]
> > * Libor detected that the dekorate version was wrong.
> 
> Is it fixed or this problem will be back for the release 2.3.X ? What can we do in the future to control/check before to build ? @jacobdotcosta

2.3.4 will have a different dekorate version which is being stablished from the input gathered in the JIRA.

**Comment by jacobdotcosta** [comment]
> > * On the update of the launcher-booster-catalog Chris realized that the upstream examples were wrong. This happened because I didn't launch the `update for release` command after releasing the upstream project.
> 
> How can we avoid that for a future release ? @jacobdotcosta

It's documented so unless we automatize it further or make some kind of interactive workflow I don't think there's much more we can do. Either that or a punch in the face next time I don't follow a step from the document.

**Comment by jacobdotcosta** [comment]
Decisions:
- merge the checklist with the main document, highlighting the tasks
- build a check list, probably from the headers of the document

**Comment by jacobdotcosta** [comment]
Our server won't be affected by the migration.
