### ISSUE TITLE
Investigate how we will productize Spring Boot using CPaas, Containerized CSB Jenkins

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/team#268]
### CPaas
- [ ] Ability to have access to the staging PNC environment from a CPaas Jenkins JOB ? If yes, how ?
  - We have 2 Jenkins jobs to launch PNC build, one against PNC production and the other against staging. Will we be able to use the PNC staging environment with CPaaS?
    - Staging has an independent `build-config.yaml` file. The main reason is because the SCM URL is different between staging and prod PNC environments, but also it is used to test changes to the build-config itself.
- [ ] Can we add our own Jenkins Job ? If yes, how ? Is Groovy DSL Supported ?

### Jenkins

- [ ] Which Jenkins jobs are still needed as some are not longer used since 2018, beginning of this year ?
       ![Screenshot 2020-10-12 at 09.30.48.png](https://images.zenhubusercontent.com/5d9c4194c1eccb0001c6d5fa/0bd6b2c5-daac-4f9b-9727-6f9b3d5568d8)
     - listen-to-bom-release         
     - upload-to-candidates
     - update-single-booster-licenses
     - update-boosters-licenses
     - Gate check Q&A
- [ ] Do we still use group of tests : `Prod-tests` and `Upstream-tests` ? 

### Docker
- [ ] Is the following [image](https://gitlab.cee.redhat.com/middleware/productization-jenkins-docker#jenkins-image-for-product-files-generator) including DA, Brew, Python still needed to productize

**Comment by cmoulliard** [comment]
Can you review the questions please ? @jacobdotcosta

**Comment by jacobdotcosta** [comment]
> ### Docker
> * [ ]  Is the following [image](https://gitlab.cee.redhat.com/middleware/productization-jenkins-docker#jenkins-image-for-product-files-generator) including DA, Brew, Python still needed to productize

From the Build History, that job is being used by Libor to generate the comparison report.

**Comment by jacobdotcosta** [comment]
From the list of Jenkins jobs, the ones we're using now are:

- run-bacon
- run-bacon-stage
- build-pfg

The other ones haven't been run at least since April 2020.

**NOTE**: I'm not sure we need to launch the build from the image that results from launching the `build-pfg` job. When I migrated to PNC 2 I wasn't able to test this since PNC staging didn't work OK so I kept this job structure.

**Comment by cmoulliard** [comment]
> From the Build History, that job is being used by Libor to generate the comparison report.

Can you then ask to Libor what he is exactly doing to generate the diff ? Which application he uses and software ? @jacobdotcosta

**Comment by cmoulliard** [comment]
> I'm not sure we need to launch the build from the image that results from launching the `build-pfg` job. When I migrated to PNC 2 I wasn't able to test this since PNC staging didn't work OK so I kept this job structure.

Can you then be more precise and add link to the image used and why it should be used ? @jacobdotcosta

**Comment by cmoulliard** [comment]
> From the list of Jenkins jobs, the ones we're using now are:
> 
> * run-bacon
> * run-bacon-stage
> * build-pfg

So the question that we should have now is : If we only run these jobs on jenkins, could we also run them using CPaas ? @jacobdotcosta 

> From the Build History, that job is being used by Libor to generate the comparison report.

Sorry Antonio but my question has nothing todo with a a Job ;-)

**Comment by jacobdotcosta** [comment]
> > From the Build History, that job is being used by Libor to generate the comparison report.
> 
> Sorry Antonio but my question has nothing todo with a a Job ;-)

I have removed that comment short after posting it when I realized my comment was incorrect.

**Comment by jacobdotcosta** [comment]
> > From the list of Jenkins jobs, the ones we're using now are:
> > 
> > * run-bacon
> > * run-bacon-stage
> > * build-pfg
> 
> So the question that we should have now is : If we only run these jobs on jenkins, could we also run them using CPaas ? @jacobdotcosta

Since we're discussing improving the automation of the productization process, and simplifying it so we don't have several tools, should we plan migrating these steps to the automation-client instead?

**Comment by cmoulliard** [comment]
> automation-client instead?

What is the automation client (= link to the tool, project) ? @jacobdotcosta

**Comment by jacobdotcosta** [comment]
The Typescript Atomist client that we already use to update the `pom.xml` and release the examples.
https://github.com/snowdrop/snowdrop-automation-client

**Comment by cmoulliard** [comment]
> The Typescript Atomist client that we already use to update the `pom.xml` and release the examples.
> https://github.com/snowdrop/snowdrop-automation-client

The problem that we will have then will be that such a tool cannot access the VPN. Dont forget also that soon it will be needed to use [CPaas](https://docs.engineering.redhat.com/pages/viewpage.action?spaceKey=CPROD&title=Continuous-Productization-as-a-Service) (MW CI/CD platform) to [productize](https://gitlab.cee.redhat.com/cpaas/documentation/-/blob/master/users/getting_started.adoc) and this is mandatory. I still dont know how we can script using CPaas but I dont see how we could capitalize from the work done using Atomist here as Atomist is an external CI/CD platform ...

@jacobdotcosta @metacosm @gytis @geoand

**Comment by cmoulliard** [comment]
When we will migrate to CPaas, it will not be needed anymore that we continue to use our OpenStack instance as CPaas will create a PSI cluster for [us](https://gitlab.cee.redhat.com/cpaas/documentation/-/blob/master/users/getting_started.adoc#user-content-onboarding-actions-by-cpaas) under `https://paas.psi.redhat.com/console/project/cpaas-<project-id>/overview` like also a jenkins instance - `https://jenkins-cpaas-<product-id>.cloud.paas.psi.redhat.com`

To be discussed with the team of course ;-)

**Comment by jacobdotcosta** [comment]
From the documentation we also need to use the CPaaS Midstream to get the changes from the upstream project.
