### ISSUE TITLE
GameOn CoLab Involvement.

### ISSUE THREAD

**Issue by BarDweller** [snowdrop/team#273]
>CO.LAB introduces middle school girls to the principles of open source—and to a world of technology and collaboration they might not have considered otherwise. Students learn how to work together to solve problems, develop new ideas, and seek shared experiences to create something unique.

This year, CO.LAB is using GameOn to provide a socially distanced collaborative experience, I'm making some updates to the core services to enable 'story mode' for them, where a custom login leads to their own shared text adventure story that they solve together collaboratively.

**Comment by BarDweller** [comment]
Ran for RedHat week in 2020, follow up in 1Q2021 for some discussion re hosting for GameOn / YamlRoom.

**Comment by cmoulliard** [comment]
As this event is over, why do you keep this task open ? @BarDweller

**Comment by BarDweller** [comment]
Oops.. I've been filtering by the buildpack epic.. 
There are still some ongoing tasks here, but not large enough to be worthy of Issues. 
Next big thing for GameOn is likely to be the server move to the CoLab k8s instance. I'll raise something to track that when it comes round.
