### ISSUE TITLE
Spring on Quarkus / Spring Data / Support nested camel-case properties in entities

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop/team#299]
https://github.com/quarkusio/quarkus/issues/13067

**Comment by renegrob** [comment]
It seems that `io.quarkus.spring.data.deployment.MethodNameParser.handleFieldsHierarchy`does not process the property path correctly. For `ownerTenantI`it produces `owner.tenantid.`instead of `.owner.tenant.id`. I think it is a problem with the dot handling when combining the fieldInf values.

**Comment by renegrob** [comment]
Hi @aureamunoz 
Since this issue was blocking us, I solved it in my fork: https://github.com/renegrob/quarkus/tree/quarkus-issue-13067. 
Now the nested fields are resolved iteratively. Please, let me know if this is of any help and I should do a draft pull request.
Best regards,
René

**Comment by aureamunoz** [comment]
Hi @renegrob 

Oh, thank you very much and sorry for the delay. I had not very much time last week for working on it.
Yes, please, you can open a draft pull request, I'll try to take a look today!

**Comment by aureamunoz** [comment]
I've just seen also the message posted on the issue thread ;-)
