### ISSUE TITLE
Create a How to guide/page explaining how to use https://github.com/BarDweller/java-buildpack-client

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/team#317]
## TODO

- Create a How to guide/page explaining how to use https://github.com/BarDweller/java-buildpack-client.
- It should include an example, pre-requisites, dekorate maven dependency to generate the kubernetes resources to deploy it on k8s

**Comment by BarDweller** [comment]
README.md for https://github.com/BarDweller/java-buildpack-client updated with basic usage overview, and links to fluent builder api source page. Should be relatively self-explanatory from here.

**Comment by BarDweller** [comment]
Leaving this one open to discuss what's still needed.. as a library it should probably be in maven, or should at least document how to use it via jitpack for now.

Unclear how dekorate will play against a buildpack built java project.. I'll raise a new sub item for investigation for that.

**Comment by BarDweller** [comment]
Meeting planned for 1st of Feb to discuss buildpack strategy for redhat buildpacks.

**Comment by cmoulliard** [comment]
> Meeting planned for 1st of Feb to discuss buildpack strategy for redhat buildpacks.

Who is invited ? Can you move it to Tuesday next week please ?

**Comment by BarDweller** [comment]
@cmoulliard If you're not invited to the next one (Wednesday), and want to be, let me know, and I'll pass on the request.

**Comment by cmoulliard** [comment]
> If you're not invited to the next one (Wednesday), and want to be, let me know, and I'll pass on the request.

Invite me as optional. Chris, Ioannis, Harris and you should be there ;-)

**Comment by cmoulliard** [comment]
> * It should include an example, pre-requisites, dekorate maven dependency to generate the kubernetes resources to deploy it on k8s

A README page exists but we dont have yet the `How To Guide` explaining how from scratch we could use the java client with a real example, ... @BarDweller

**Comment by BarDweller** [comment]
I've added a quick How To, but we may need to discuss further what you are after. 

It should include;
- an example
  - An example was included in the readme, the new how to section explains a bit more, including usage via jitpack (until the library is published to maven central, but I want to get the package name settled before we do that)
- pre-requisites, 
  - Code dependency wise, that's all handled by maven. 
  - Runtime dependency is just Docker, with a Docker socket, already mentioned in the readme. 
    - You could argue the Builder image/Run image are also dependencies, but they are customizable, and the defaults are in dockerhub.
- dekorate maven dependency to generate the kubernetes resources to deploy it on k8s
  - this would be a function of the project being built, not the of the java-buildpack-client itself, the buildpack build doesn't care if dekorate is used or not.

**Comment by BarDweller** [comment]
Closing this, as the readme is pretty comprehensive, and the lib has been moved to snowdrop and released to maven central. We can track additional requirements/enhancements via Issues on it's repo https://github.com/snowdrop/java-buildpack-client
