### ISSUE TITLE
Provide feedback / assist with updates to Buildpack platform spec.

### ISSUE THREAD

**Issue by BarDweller** [snowdrop/team#322]
The Buildpack platform spec is a little .. difficult .. to work with currently. The spec appears to impose requirements on the Platform implementation that cannot be met. Need to work with the buildpack project to assist them in clarifications / improvements to the spec, so that we can properly claim compliance to it. 

Note currently there are 4 implementations I'm aware of, `pack`, the tekton impl(s), the spring boot plugin impls, and the library being created by this epic. 

In discussions with the platform spec authors via their slack (buildpacks.slack.com), it would seem they are open to feedback / assistance in updating the spec.

**Comment by BarDweller** [comment]
Opened https://github.com/buildpacks/spec/issues/165 to detail current issues with the platform spec, as a start point for discussion / conversion into RFC.

**Comment by BarDweller** [comment]
Passed on additional feedback related to Buildpacks stacks spec, as I started digging into buildpack creation for Quarkus

**Comment by cmoulliard** [comment]
What is the status of this task (accomplish, ...) ? If job is done, then close it please as it appears every week while in fact the work is done @BarDweller

**Comment by BarDweller** [comment]
Agreed, there is ongoing discussion now with Buildpack team thats not really capturable here, feedback was well received, however, no real updates have come from them as a result of the feedback yet, which looks like a lack of resource on their side to tackle what would become a 3 way spec rewrite across their public specs. 

Closing this one here. Goal achieved.
