### ISSUE TITLE
Read/understand productization process

### ISSUE THREAD

**Issue by yharish991** [snowdrop/team#365]
Release docs link https://gitlab.cee.redhat.com/snowdrop/infra-prod/-/blob/master/prod/release-process.md

**Comment by cmoulliard** [comment]
This task like also creating jobs is high priority. Can you then please work on it ?

**Comment by yharish991** [comment]
prs are on the way for epic https://app.zenhub.com/workspaces/snowdrop-5e13555db24025e26165460f/issues/snowdrop/team/362
