### ISSUE TITLE
Create technical design doc describing servicebinding inside the Spring boot application

### ISSUE THREAD

**Issue by yharish991** [snowdrop/team#400]

**Comment by cmoulliard** [comment]
Can you add the link to the document created please ? As this task has been accomplish (except voting result), can you then park it to `done` ? Did you get votes ?

**Comment by yharish991** [comment]
Link to the doc https://docs.google.com/document/d/1H3a2hcz7GnS-odxi7131ebSDtBWYXBU9bJxyFYvXf2o/edit?usp=sharing .  Chris and Georgios voted, waiting for others.. @iocanel @BarDweller @zekaguilar can you guys cast your votes in the doc when you get a chance? :)

**Comment by yharish991** [comment]
technical document created, so closing this issue
