### ISSUE TITLE
Dekorate introduction talk for DevConf.CZ

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop/team#430]
Friday 19th of February I will attend the conf for being present during the talk and responding questions after the talk

**Comment by cmoulliard** [comment]
Can you share here the feedback about your talk please ? @aureamunoz

**Comment by aureamunoz** [comment]
Yes but I didn't have too many feedbacks, just a few of 'great talk!' and the question that I shared in the `dekorate` thread of Zulip:
Is it possible to use an alternatif properties file, for example: src/test/resources/application-build.properties?
