### ISSUE TITLE
Improving the snowdrop tests made by ENG

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#47]
In the last release some errors where detected in an early QA stage that seemed basic to identify.

Would it make sense to improve the marete tests / or a new set of ENG tests, to try detect these errors prior to arriving to QA?

- [x] Marete tests - blocked by https://gitlab.cee.redhat.com/rhoar-qe/marete/-/issues/2
- [x] productized build comparison with previous validation
- [x] productized build duplication validation
- ~[ ] Verify the launcher examples against temporary release builds (CR1, CR2, ...) ~

**Comment by cmoulliard** [comment]
Do you have a list of tests to be included ? Where ? Should we automated them ? @jacobdotcosta

**Comment by jacobdotcosta** [comment]
This will be discussed as part of the release automation process.
