### ISSUE TITLE
Investigate client side service discovery and load balancing in Spring

### ISSUE THREAD

**Issue by gytis** [snowdrop/team#485]
Needed for https://github.com/quarkusio/quarkus/issues/16150

- [ ]  See how does Feign do service discovery (Eureka) and load balancing (Ribbon)

**Comment by cmoulliard** [comment]
I think that Spring is using now their own Lib part of the Spring Cloud Gateway (https://spring.io/guides/gs/gateway/, https://cloud.spring.io/spring-cloud-gateway/reference/html/) to :

- discover - https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-discoveryclient-route-definition-locator 
- loadbalance - https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-loadbalancerclient-filter

Do you confirm ? @gytis 

Hmhmhm: It seems that we still need OpenFeign, Consul Discovery Server, Netflix ribbon ... https://piotrminkowski.com/2019/11/06/microservices-with-spring-boot-spring-cloud-gateway-and-consul-cluster/

**Comment by gytis** [comment]
I looked specifically in OpenFeign because we're implementing a client side service discovery and load balancing and that is what Feign uses.
