### ISSUE TITLE
Evaluate the Buildpacks RFC supporting privileged users, new stack to build, ...

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/team#494]
## TODO

- Evaluate the Buildpacks RFC supporting privileged users, new stack to build, ...
- Reference: https://github.com/buildpacks/rfcs/blob/main/text/0069-stack-buildpacks.md
- Discuss with Ozzy what we could design around that

**Comment by BarDweller** [comment]
Closing this too, Stackpacks died a slow death, and was replaced by the 'Dockerfile RFC' which is currently in Phase 1 of delivery.
