### ISSUE TITLE
Create a proposal on aligning Dekorate, JKube and Quarkus

### ISSUE THREAD

**Issue by iocanel** [snowdrop/team#657]

**Comment by cmoulliard** [comment]
Can you please add the proposal document or github issue part of the description like also what will be the next steps (meeting, ...) ? @iocanel

**Comment by iocanel** [comment]
https://docs.google.com/document/d/1yDAW2RUF0WeFXWGLcRJcAGB4-zfstc4ZLMg46OV7NAk/edit
