### ISSUE TITLE
Update the build configuration for release 2.5.8.DR1

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#668]
Update the build-configuration with the collected versions for release the first `2.5.8` DR release.

**Comment by jacobdotcosta** [comment]
https://gitlab.cee.redhat.com/middleware/build-configurations/-/merge_requests/666

**Comment by cmoulliard** [comment]
Can you be a bit more verbose as the title do not explain is you ask something from a peer or want to inform them ? @jacobdotcosta
