### ISSUE TITLE
Release for 2.5.8 depends on AMQP pending reply

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#686]
Release 2.5.8 depends on AMQP which haven't replied to our information request ticket.

**Comment by cmoulliard** [comment]
Instead of creating 3 separate issue, simply create an issue containing as title `Release 2.8 still blocked due to lack of feedback or 3rd party release delayed from projects` and within the description list the projects that you are still waiting a response @jacobdotcosta
