### ISSUE TITLE
Openstack Jenkins instance isn't responding

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#747]
Trying to test the changes to the Helm chart that provisions Jenkins for Upstream releases I realize it isn't responding neither to `kubectl` requests on port 6443 nor ven to ssh requests on port 22.

```bash
$ kubectl get nodes
Unable to connect to the server: dial tcp 10.0.76.30:6443: i/o timeout
```

```bash
$ ssh centos@10.0.76.30
ssh: connect to host 10.0.76.30 port 22: Connection timed out
```

**Comment by cmoulliard** [comment]
Is it possible that you move the highlighted text to a comment, otherwise it is displayed by the new reporting tool ?
