### ISSUE TITLE
Quarkus extension for Helm

### ISSUE THREAD

**Issue by Sgitario** [snowdrop/team#750]
Extension created at https://github.com/quarkiverse/quarkus-helm
Not released yet because it needs Quarkus 2.8 which will be out in March. 
ETA: 2-3 weeks
{issues}
- https://github.com/quarkusio/quarkus/pull/23657
- https://github.com/quarkusio/quarkus/pull/23570
- https://github.com/dekorateio/dekorate/pull/864
- https://github.com/quarkusio/quarkus/issues/23540
- https://github.com/quarkiverse/quarkus-helm/issues/2
{/issues}

**Comment by cmoulliard** [comment]
When do you plan to release Quarkus extension for Helm ? @Sgitario

**Comment by Sgitario** [comment]
I will be able to finish off this extension once a new version of Quarkus is released which should include the changes that were merged yesterday in https://github.com/quarkusio/quarkus/pull/23657
