### ISSUE TITLE
Red Hat Talk in Barcelona University

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop/team#775]
I'm talking with some others Red Hatters at the University in Barcelona, next 24th of March. Started to work on it.

**Comment by cmoulliard** [comment]
Can you detailed what you talked about ? @aureamunoz

**Comment by aureamunoz** [comment]
I have presented the Opensource projects: 
- What is opensource
- How we work in Red Hat regarding open source projects contributions
- Tips for choosing a project to contribute
- Git workflow
- Tips for contributing (do code reviews, contribute to the documentation, tests...)
- Some good projects to start contributing
