### ISSUE TITLE
Discuss with SRE team about Java operators concerns mentioned during EKO

### ISSUE THREAD

**Issue by Sgitario** [snowdrop/team#786]
Some concerns were raised during the EKO presentation that Java operators might be a problem for the SRE team, so followed up on the topic to assuage any concerns. 

Resolution: language in which operators are written is not an issue, it's more about patterns (observability, in particular) and expectations. Amber Krawczyk sent an email to the EKO mailing list on the topic.

**Comment by cmoulliard** [comment]
> so followed up on the topic to assuage any concerns

Can you elaborate what you did here (meeting, email, ...) and what was the outcome ? @metacosm

**Comment by metacosm** [comment]
> > so followed up on the topic to assuage any concerns
> 
> Can you elaborate what you did here (meeting, email, ...) and what was the outcome ? @metacosm

I'm not sure what more I could say that is already said here: https://github.com/snowdrop/team/issues/786#issue-1183540129, though I did update the comment for clarity.

**Comment by csviri** [comment]
What do you mean "it's more about patterns and expectations" ?  @Sgitario

**Comment by cmoulliard** [comment]
Can you post the content of the email of Amber Krawczyk ?

**Comment by metacosm** [comment]
> Can you post the content of the email of Amber Krawczyk ?

Why, you should have received it?

**Comment by cmoulliard** [comment]
> Why, you should have received it?

Under mw-eko <mw-eko@redhat.com> ?
