### ISSUE TITLE
Check jboss-set/aphrodite support for GitHub discussions and projects

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#79]
Check if the [jboss-set/aphrodite](https://github.com/jboss-set/aphrodite) github project can support GitHub discussions and project manipulation

**Comment by cmoulliard** [comment]
> Check if the [jboss-set/aphrodite](https://github.com/jboss-set/aphrodite) github project can support GitHub discussions and project manipulation

This is not the case. We should in this case work on this ticket - https://github.com/hub4j/github-api/issues/828#issuecomment-635841209.

**Comment by cmoulliard** [comment]
I submitted a PR - https://github.com/hub4j/github-api/pull/834

**Comment by cmoulliard** [comment]
I think that you can close this ticket @jacobdotcosta

**Comment by jacobdotcosta** [comment]
I did a review when implementing the CVE report on the issues manager and aphrodite lacked some functionalities available in the `org.kohsuke:github-api` that's why I ended up using this library instead.
