### ISSUE TITLE
Participate to a Stork call with Marketing Technical team 

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop/team#803]
We have been contacted by Jeff Beck and we had a call to speak about Stork content. Here the mail we had: 

The RHBQ 2.7 release is coming up and the Runtimes marketing team is putting together a marketing plan to highlight its capabilities. Part of this plan is to do a technical deep dive on 2 or 3 impactful features of the release.

One of the topics we would like to do a deep dive on is "SmallRye Stork". We would love to have you partner up with one of our technical marketing team members to create technical content for this topic.

Here are the details:

    audience: experienced Java developers with Quarkus familiarity
    content:
        demo video (10-15 mins max)
        blog post for [dev.rh.com](http://dev.rh.com/) (content TBD)
        (if necessary) informational slides - what/why it is important to devs? 
        other - we are open to other content ideas
    timeframe: 3-4 weeks to deliver

Let me know if you are interested or would like to point me to another resource that may be able to help.

**Comment by cmoulliard** [comment]
> Jeff

Who is Jeff ? Can you, when you report such a message mention the first and last name of the person please @aureamunoz

**Comment by aureamunoz** [comment]
> > Jeff
> 
> Who is Jeff ? Can you, when you report such a message mention the first and last name of the person please @aureamunoz

Oups, I thought having put the complete name. Jeff is Jeff Beck. I updated the description too

**Comment by cmoulliard** [comment]
> Jeff Beck

Many thanks.
