### ISSUE TITLE
WLC - Participate to the Spain WLC weekly call 

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop/team#816]
This week I have participated to this call with women from Spain Women leadership comunity. 
I have shared with them a query from Kristen Fisher and Jonathan Vila (from JBCNConf) who is searching someone to lead a Diversity Task Force. Kristen and Jonathan asked to me if I wanted to do it but I will not be able so I shared in the WLC and Pilar Bravo is going to driven this.

**Comment by cmoulliard** [comment]
> Spain Women leadership comunity

Do you have a link to this event ? @aureamunoz

**Comment by aureamunoz** [comment]
No, this is a weekly meeting. It takes place on Mondays at 11h. Usually I'm not joining because I have the 1:1 with @cmoulliard but last Monday I was available.
