### ISSUE TITLE
Call with Apple developers regarding flink operator

### ISSUE THREAD

**Issue by csviri** [snowdrop/team#828]
Had a call (will have a next) with Gyula from Apple team to discuss what is the best approach to implement state management (for a possibly non-idempotent) API for Flink operator. They are very happy with the framework, just also the flink operator covers some interesting cases regarding external resource management. This was also a good input for us.

Flink operator: https://github.com/apache/flink-kubernetes-operator

**Comment by cmoulliard** [comment]
Who is Gyula (Last and Firstname) ? @csviri

**Comment by csviri** [comment]
This guy: https://github.com/gyfora 
one of the main developers of the operator. (First contributor: https://github.com/apache/flink-kubernetes-operator/graphs/contributors )
