### ISSUE TITLE
Spring on Quarkus / Advocacy / Participate in DEAP

### ISSUE THREAD

**Issue by geoand** [snowdrop/team#84]
I was selected to be part of the `Developer Engineering Advocate Programme`. This means I need to dedicate a few hours each week or two.

**Comment by cmoulliard** [comment]
What is the status of the DEAP mission ? @geoand

**Comment by geoand** [comment]
I am waiting for Tiffany Jacob to assign me to a new customer

**Comment by cmoulliard** [comment]
> I am waiting for Tiffany Jacob to assign me to a new customer

So I propose to close this task to re-open it when you will effectively work for a DEAP customer. Make sense ? @geoand

**Comment by geoand** [comment]
Sure yeah

**Comment by cmoulliard** [comment]
An alternative is perhaps to move it then to the column `backlog` ?

**Comment by geoand** [comment]
I just closed it for now. I'll reopen when I am given a new assignment
