### ISSUE TITLE
Improve Examples for cloud native capabilities

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#861]
The idea is to improve the examples to:

- better demonstrate cloud native capabilities for kubernetes (upstream) and openshift (downstream)
- better demonstrate Dekorate capabilities deploying applications using Dekorate, Helm, etc.

**Comment by Sgitario** [comment]
As far I see, this is what the Snowdrop Examples are already doing :/

**Comment by Sgitario** [comment]
I'm closing this task as we're already covering the items mentioned in the description.
