### ISSUE TITLE
Spring on Quarkus / DevExp / Research BuildPacks

### ISSUE THREAD

**Issue by geoand** [snowdrop/team#87]
Quarkus team wants to know if we can use BuildPacks, so I need to investigate

**Comment by cmoulliard** [comment]
> Quarkus team wants to know if we can use BuildPacks, so I need to investigate

We can use it for sure but it depends how they would like to integrate `buildpack` which is a technology similar to `s2i` (dekorate, ....) ? @geoand

**Comment by geoand** [comment]
At this point it's just to see whether we shoud attempt to do anything in Quarkus and if so, how. Nothing concrete at all

**Comment by cmoulliard** [comment]
If quarkus project is interested to become part of the CloudFoundry offering and potentially others, then supporting `buildpack`, which is a sandbox CNCF project - https://www.cncf.io/sandbox-projects/,  as you already do it for [JIB](https://quarkus.io/guides/container-image) is certainly needed

**Comment by cmoulliard** [comment]
Where is the code, ... developed and waiting a review ? @geoand

**Comment by geoand** [comment]
Not every issue is about writing code, right?

**Comment by cmoulliard** [comment]
> Not every issue is about writing code, right?

Correct but as this task is part of the column `pending review`, my question is then who is gonna to review hat ?

**Comment by geoand** [comment]
Ah, correct.

TBH, I never saw that the last swim lane was called `Review Pending`. I always thought it was just `Done`, so I have been moving issues there when I am finished working on them.

**Comment by cmoulliard** [comment]
Do you then plan to move it to `done`? @geoand

**Comment by geoand** [comment]
Closed 😎

**Comment by BarDweller** [comment]
Had a quick look at this, both Spring Boot Maven Plugin and Spring Boot Gradle Plugin, use this maven dependency, https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-buildpack-platform (source: https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-tools/spring-boot-buildpack-platform )  that handles the buildpack integration. Could we reuse this?

**Comment by cmoulliard** [comment]
> Could we reuse this?

WDYM ? Could we reuse the code and integrate it within a Quarkus extension ? @BarDweller
