### ISSUE TITLE
Review the supported components list

### ISSUE THREAD

**Issue by gytis** [snowdrop/team#88]
https://access.redhat.com/articles/5099911

JIRA ticket: https://issues.redhat.com/browse/ENTSBT-305

**Comment by cmoulliard** [comment]
Can you describe what we should review, decisions to take, if PM is involved or not, ... ? @gytis

**Comment by gytis** [comment]
I found a message from Naina this morning asking for me to review the supported component list to confirm that all the entries are correct.

**Comment by gytis** [comment]
Ticket is assigned to me
